### ISSUE TITLE
Low performance with long working

### ISSUE THREAD

**Issue by vasiliy0s** [alienhard/SublimeAllAutocomplete#43] opened 2015-03-10 08:31 UTC
I have performance issue after several minutes of working with ST3. After module disabling and ST fully restarted, issues leave off. In work I can open many JavaScript files. 

I'm using ST on my MacMini, but with more powerfull machine under Ubuntu I have not this problem with many files.

**Comment by magadanskiuchen** [comment] 2015-04-14 06:45
I'm experiencing the same issue.

It started when I updated Sublime to Build 3083 (earlier builds of SublimeText 3 seem to work OK).

It seems this happens when switching between projects.

**Comment by alienhard** [comment] 2015-06-02 05:16
hey @vasiliy0s and @magadanskiuchen 

I'm trying to reproduce with Build 3083... I opened 70 files but didn't see a slowdown (on a MacBook Pro).

Do you have a performance issue with ST in general or just with autocomplete? (What exactly is slow?)
When you say "many files", is this like 100 open files or is it more?

**Comment by magadanskiuchen** [comment] 2015-06-03 18:37
My case it was thousands of files -- most of them were just media assets, but this still seemed to have resulted in rather big memory consumption.

The total size of the folder, which was added to the Sublime Text project was about 7GB.

I do realize that some performance penalty in such cases should be expected but if you can check if a file is binary and skip fully reading (if this is not done already) it this should be good enough solution.

**Comment by canoeberry** [comment] 2016-12-05 08:05
You had thousands of files open at once in Sublime?

This plugin only searches files that are currently in views. And it stops the search at 20 views.

**Comment by alienhard** [comment] 2016-12-05 22:59
Closing this ticket – slowness hasn't been reported since we added this limit.

**Closed by alienhard** 2016-12-05 22:59 UTC
